"""add unique constraint to clan name

Revision ID: 85733227cdf9
Revises: 8fb87bf75397
Create Date: 2025-12-26 23:01:48.188385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85733227cdf9'
down_revision: Union[str, Sequence[str], None] = '8fb87bf75397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_clans_name', 'clans', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clans_name', 'clans', type_='unique')
    # ### end Alembic commands ###
